services:
  frontend:
    build:
      context: ./arvisan-frontend
      # No target here; overridden in dev/test files
    restart: 'unless-stopped'
    networks:
      - arvisan
  backend:
    build:
      context: ./arvisan-backend
    restart: 'unless-stopped'
    networks:
      - arvisan
    environment:
      - NEO4J_URL=bolt://host.docker.internal:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=ChangeMe!Ord0nt
      - NEO4J_QUERY_TIMEOUT=10000
      - HTTP_BASIC_AUTH_USERNAME=test_user
      - HTTP_BASIC_AUTH_PASSWORD=test_password
      - HTTP_FRONTEND_URL=http://localhost:5173
      - UNCATEGORIZED_DOMAIN_NODE_NAME=no_domain
      - GRAPH_IMPORT_LOCATION=/import
    volumes:
      - neo4j_import:/import
    ports:
      - 5174:3000
  neo4j:
    image: neo4j:latest
    restart: 'unless-stopped'
    networks:
      - arvisan
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/ChangeMe!Ord0nt
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_plugins:
    driver: local
  neo4j_import:
    driver: local

networks:
  arvisan:
    driver: bridge